using System;
using System.Collections;
using System.Collections.Generic;
using FreeNet;

namespace FreeNetUnity
{
	public enum NETWORK_EVENT : byte
	{
		// Connection established.
		connected,

		// Connection disconnected.
		disconnected,

		// End.
		end
	}

	/// <summary>
	/// Queues events generated by the network engine.
	/// This class can be called from both worker threads and the main thread,
	/// so thread synchronization is applied.
	/// </summary>
	public class CFreeNetEventManager
	{
		// Synchronization object.
		object cs_event;

		// Queue to store events generated by the network engine.
		Queue<NETWORK_EVENT> network_events;

		// Queue to store packets received from the server.
		Queue<CPacket> network_message_events;

		public CFreeNetEventManager()
		{
			this.network_events = new Queue<NETWORK_EVENT>();
			this.network_message_events = new Queue<CPacket>();
			this.cs_event = new object();
		}

		public void enqueue_network_event(NETWORK_EVENT event_type)
		{
			lock (this.cs_event)
			{
				this.network_events.Enqueue(event_type);
			}
		}

		public bool has_event()
		{
			lock (this.cs_event)
			{
				return this.network_events.Count > 0;
			}
		}

		public NETWORK_EVENT dequeue_network_event()
		{
			lock (this.cs_event)
			{
				return this.network_events.Dequeue();
			}
		}


		public bool has_message()
		{
			lock (this.cs_event)
			{
				return this.network_message_events.Count > 0;
			}
		}

		public void enqueue_network_message(CPacket buffer)
		{
			lock (this.cs_event)
			{
				this.network_message_events.Enqueue(buffer);
			}
		}

		public CPacket dequeue_network_message()
		{
			lock (this.cs_event)
			{
				return this.network_message_events.Dequeue();
			}
		}
	}
}
